@startuml
!include common-style.puml
title Дерево решений при ответе med-robot

start
:Локальный выбор получен;
if (med-robot включен?) then (да)
  if (Запрос успешен?) then (да)
    if (serviceId в маршруте?) then (да)
      if (queueId известен?) then (да)
        :Принять результат\nserviceId + queueId;
        stop
      else (нет)
      endif
    else (нет)
    endif
  else (нет)
  endif
endif
:Fallback\nлокальный алгоритм;
stop
@enduml
